# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: deploy-test
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set release version
      run:  mvn -B versions:set -DnewVersion=3.0.0 -DgenerateBackupPoms=false

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate settings.xml for Deployment
      run: echo "<settings><servers><server><id>central</id><username>${{ secrets.MAVEN_USERNAME }}</username><password>${{ secrets.MAVEN_PASSWORD }}</password></server></servers></settings>" > $GITHUB_WORKSPACE/settings.xml

    - name: Prepare GPG Key
      run: echo "${{ secrets.MAVEN_GPG_KEY_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/maven-gpg.key

    - name: Head
      run: head -n 3 $GITHUB_WORKSPACE/maven-gpg.key

    - name: Tail
      run: tail -n 3 $GITHUB_WORKSPACE/maven-gpg.key

    - name: Publish to Maven Central
      run: mvn -P release deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
#        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_GPG_KEY: $GITHUB_WORKSPACE/maven-gpg.key
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
